// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cvparser

import (
	"github.com/germainlefebvre4/cvwonder/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewParserInterfaceMock creates a new instance of ParserInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParserInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParserInterfaceMock {
	mock := &ParserInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ParserInterfaceMock is an autogenerated mock type for the ParserInterface type
type ParserInterfaceMock struct {
	mock.Mock
}

type ParserInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ParserInterfaceMock) EXPECT() *ParserInterfaceMock_Expecter {
	return &ParserInterfaceMock_Expecter{mock: &_m.Mock}
}

// ParseFile provides a mock function for the type ParserInterfaceMock
func (_mock *ParserInterfaceMock) ParseFile(filePath string) (model.CV, error) {
	ret := _mock.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for ParseFile")
	}

	var r0 model.CV
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (model.CV, error)); ok {
		return returnFunc(filePath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) model.CV); ok {
		r0 = returnFunc(filePath)
	} else {
		r0 = ret.Get(0).(model.CV)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(filePath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ParserInterfaceMock_ParseFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseFile'
type ParserInterfaceMock_ParseFile_Call struct {
	*mock.Call
}

// ParseFile is a helper method to define mock.On call
//   - filePath
func (_e *ParserInterfaceMock_Expecter) ParseFile(filePath interface{}) *ParserInterfaceMock_ParseFile_Call {
	return &ParserInterfaceMock_ParseFile_Call{Call: _e.mock.On("ParseFile", filePath)}
}

func (_c *ParserInterfaceMock_ParseFile_Call) Run(run func(filePath string)) *ParserInterfaceMock_ParseFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ParserInterfaceMock_ParseFile_Call) Return(cV model.CV, err error) *ParserInterfaceMock_ParseFile_Call {
	_c.Call.Return(cV, err)
	return _c
}

func (_c *ParserInterfaceMock_ParseFile_Call) RunAndReturn(run func(filePath string) (model.CV, error)) *ParserInterfaceMock_ParseFile_Call {
	_c.Call.Return(run)
	return _c
}

// convertFileContentToStruct provides a mock function for the type ParserInterfaceMock
func (_mock *ParserInterfaceMock) convertFileContentToStruct(content []byte) model.CV {
	ret := _mock.Called(content)

	if len(ret) == 0 {
		panic("no return value specified for convertFileContentToStruct")
	}

	var r0 model.CV
	if returnFunc, ok := ret.Get(0).(func([]byte) model.CV); ok {
		r0 = returnFunc(content)
	} else {
		r0 = ret.Get(0).(model.CV)
	}
	return r0
}

// ParserInterfaceMock_convertFileContentToStruct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'convertFileContentToStruct'
type ParserInterfaceMock_convertFileContentToStruct_Call struct {
	*mock.Call
}

// convertFileContentToStruct is a helper method to define mock.On call
//   - content
func (_e *ParserInterfaceMock_Expecter) convertFileContentToStruct(content interface{}) *ParserInterfaceMock_convertFileContentToStruct_Call {
	return &ParserInterfaceMock_convertFileContentToStruct_Call{Call: _e.mock.On("convertFileContentToStruct", content)}
}

func (_c *ParserInterfaceMock_convertFileContentToStruct_Call) Run(run func(content []byte)) *ParserInterfaceMock_convertFileContentToStruct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *ParserInterfaceMock_convertFileContentToStruct_Call) Return(cV model.CV) *ParserInterfaceMock_convertFileContentToStruct_Call {
	_c.Call.Return(cV)
	return _c
}

func (_c *ParserInterfaceMock_convertFileContentToStruct_Call) RunAndReturn(run func(content []byte) model.CV) *ParserInterfaceMock_convertFileContentToStruct_Call {
	_c.Call.Return(run)
	return _c
}

// readFile provides a mock function for the type ParserInterfaceMock
func (_mock *ParserInterfaceMock) readFile(filePath string) []byte {
	ret := _mock.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for readFile")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// ParserInterfaceMock_readFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'readFile'
type ParserInterfaceMock_readFile_Call struct {
	*mock.Call
}

// readFile is a helper method to define mock.On call
//   - filePath
func (_e *ParserInterfaceMock_Expecter) readFile(filePath interface{}) *ParserInterfaceMock_readFile_Call {
	return &ParserInterfaceMock_readFile_Call{Call: _e.mock.On("readFile", filePath)}
}

func (_c *ParserInterfaceMock_readFile_Call) Run(run func(filePath string)) *ParserInterfaceMock_readFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ParserInterfaceMock_readFile_Call) Return(bytes []byte) *ParserInterfaceMock_readFile_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *ParserInterfaceMock_readFile_Call) RunAndReturn(run func(filePath string) []byte) *ParserInterfaceMock_readFile_Call {
	_c.Call.Return(run)
	return _c
}
