// Code generated by mockery v2.53.5. DO NOT EDIT.

package cvbulk

import (
	cvbulk "github.com/germainlefebvre4/cvwonder/internal/cvbulk"
	mock "github.com/stretchr/testify/mock"

	model "github.com/germainlefebvre4/cvwonder/internal/model"
)

// BulkGenerateInterfaceMock is an autogenerated mock type for the BulkGenerateInterface type
type BulkGenerateInterfaceMock struct {
	mock.Mock
}

type BulkGenerateInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *BulkGenerateInterfaceMock) EXPECT() *BulkGenerateInterfaceMock_Expecter {
	return &BulkGenerateInterfaceMock_Expecter{mock: &_m.Mock}
}

// BulkGenerate provides a mock function with given fields: inputFiles, inputDir, outputDir, themeName, format, validate, concurrency
func (_m *BulkGenerateInterfaceMock) BulkGenerate(inputFiles []model.InputFile, inputDir string, outputDir string, themeName string, format string, validate bool, concurrency int) []cvbulk.BulkResult {
	ret := _m.Called(inputFiles, inputDir, outputDir, themeName, format, validate, concurrency)

	if len(ret) == 0 {
		panic("no return value specified for BulkGenerate")
	}

	var r0 []cvbulk.BulkResult
	if rf, ok := ret.Get(0).(func([]model.InputFile, string, string, string, string, bool, int) []cvbulk.BulkResult); ok {
		r0 = rf(inputFiles, inputDir, outputDir, themeName, format, validate, concurrency)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cvbulk.BulkResult)
		}
	}

	return r0
}

// BulkGenerateInterfaceMock_BulkGenerate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkGenerate'
type BulkGenerateInterfaceMock_BulkGenerate_Call struct {
	*mock.Call
}

// BulkGenerate is a helper method to define mock.On call
//   - inputFiles []model.InputFile
//   - inputDir string
//   - outputDir string
//   - themeName string
//   - format string
//   - validate bool
//   - concurrency int
func (_e *BulkGenerateInterfaceMock_Expecter) BulkGenerate(inputFiles interface{}, inputDir interface{}, outputDir interface{}, themeName interface{}, format interface{}, validate interface{}, concurrency interface{}) *BulkGenerateInterfaceMock_BulkGenerate_Call {
	return &BulkGenerateInterfaceMock_BulkGenerate_Call{Call: _e.mock.On("BulkGenerate", inputFiles, inputDir, outputDir, themeName, format, validate, concurrency)}
}

func (_c *BulkGenerateInterfaceMock_BulkGenerate_Call) Run(run func(inputFiles []model.InputFile, inputDir string, outputDir string, themeName string, format string, validate bool, concurrency int)) *BulkGenerateInterfaceMock_BulkGenerate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]model.InputFile), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(bool), args[6].(int))
	})
	return _c
}

func (_c *BulkGenerateInterfaceMock_BulkGenerate_Call) Return(_a0 []cvbulk.BulkResult) *BulkGenerateInterfaceMock_BulkGenerate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BulkGenerateInterfaceMock_BulkGenerate_Call) RunAndReturn(run func([]model.InputFile, string, string, string, string, bool, int) []cvbulk.BulkResult) *BulkGenerateInterfaceMock_BulkGenerate_Call {
	_c.Call.Return(run)
	return _c
}

// NewBulkGenerateInterfaceMock creates a new instance of BulkGenerateInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBulkGenerateInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *BulkGenerateInterfaceMock {
	mock := &BulkGenerateInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
