// Code generated by mockery v2.53.5. DO NOT EDIT.

package render_screenshot

import (
	model "github.com/germainlefebvre4/cvwonder/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// RenderScreenshotInterfaceMock is an autogenerated mock type for the RenderScreenshotInterface type
type RenderScreenshotInterfaceMock struct {
	mock.Mock
}

type RenderScreenshotInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RenderScreenshotInterfaceMock) EXPECT() *RenderScreenshotInterfaceMock_Expecter {
	return &RenderScreenshotInterfaceMock_Expecter{mock: &_m.Mock}
}

// RenderFormatScreenshot provides a mock function with given fields: cv, outputDirectory, inputFilename, themeName, outputFilePath
func (_m *RenderScreenshotInterfaceMock) RenderFormatScreenshot(cv model.CV, outputDirectory string, inputFilename string, themeName string, outputFilePath string) {
	_m.Called(cv, outputDirectory, inputFilename, themeName, outputFilePath)
}

// RenderScreenshotInterfaceMock_RenderFormatScreenshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderFormatScreenshot'
type RenderScreenshotInterfaceMock_RenderFormatScreenshot_Call struct {
	*mock.Call
}

// RenderFormatScreenshot is a helper method to define mock.On call
//   - cv model.CV
//   - outputDirectory string
//   - inputFilename string
//   - themeName string
//   - outputFilePath string
func (_e *RenderScreenshotInterfaceMock_Expecter) RenderFormatScreenshot(cv interface{}, outputDirectory interface{}, inputFilename interface{}, themeName interface{}, outputFilePath interface{}) *RenderScreenshotInterfaceMock_RenderFormatScreenshot_Call {
	return &RenderScreenshotInterfaceMock_RenderFormatScreenshot_Call{Call: _e.mock.On("RenderFormatScreenshot", cv, outputDirectory, inputFilename, themeName, outputFilePath)}
}

func (_c *RenderScreenshotInterfaceMock_RenderFormatScreenshot_Call) Run(run func(cv model.CV, outputDirectory string, inputFilename string, themeName string, outputFilePath string)) *RenderScreenshotInterfaceMock_RenderFormatScreenshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.CV), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *RenderScreenshotInterfaceMock_RenderFormatScreenshot_Call) Return() *RenderScreenshotInterfaceMock_RenderFormatScreenshot_Call {
	_c.Call.Return()
	return _c
}

func (_c *RenderScreenshotInterfaceMock_RenderFormatScreenshot_Call) RunAndReturn(run func(model.CV, string, string, string, string)) *RenderScreenshotInterfaceMock_RenderFormatScreenshot_Call {
	_c.Run(run)
	return _c
}

// NewRenderScreenshotInterfaceMock creates a new instance of RenderScreenshotInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRenderScreenshotInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RenderScreenshotInterfaceMock {
	mock := &RenderScreenshotInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
