---
name: Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Cache Golang dependencies
        uses: actions/cache@v4
        env:
          cache-name: cache-go-rod
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.event.number }}-${{ hashFiles('go.sum') }}
          path: |
            ~/.cache/rod
            ~/go/pkg/

      - name: Build
        run: go build -v -o cvwonder ./cmd/cvwonder

      - name: Test with the Go CLI
        run: go test ./...

      - name: Test with cvwonder
        run: |
          ./cvwonder theme install https://github.com/germainlefebvre4/cvwonder-theme-default
          ./cvwonder generate --theme default --format=html
          # ./cvwonder generate --theme default --format=pdf

          ./cvwonder serve --theme=default &
          PID=$!
          sleep 5
          kill $PID
