---
name: Go Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  pkggodev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update pkg.go.dev endpoint
        run: curl "https://proxy.golang.org/github.com/germainlefebvre4/cvwonder/@v/${{ github.ref_name }}.info"

  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
            name: cvwonder
            path: dist/*

  docker-publish:
    uses: ./.github/workflows/docker-publish.yml
    with:
      version: ${{ github.ref_name }}
    secrets: inherit
